env:
  global:
  - GCP_PROJECT_ID=devops-examen-2020
  - IMAGE=gcr.io/devops-examen-2020/card
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - DOCKER_USERNAME=guber90
  - secure: 5lVW3OG7Yp3MAkX//2G8Y6BOZlX6zulb2fqPtz5DK5SkBORkrdZAWSn8YTM7bguH1J/i7WSeSFvUSb6hHAfhTKZNKWos0lIAX3oI6SE+VhdVyGyupGi0u1L9RhHtBWm+6M4aaImPeODHqs6L+axtqy8q8jA5a4opAZeYTdomP1oMZe0b/lKb5ulTky8l6nseqkLsQzUYHCQCkJokGc3EncXasVA9em7NAAs+WzScwqnCadvW3FOl58E/HYCu4Y1ctXm0LOeeR3DaIiQu80FHeHwofNsTqcX9vQ64oTwlOES8L7Lxh/55giyd3qFeeh6tRSjOfhnmkd3uuZc6EgpYwKTQLIA2E+aiQx3JnyRGYKJfNW/dQOaRPo1UmVZsRv7tPoCDO0W4MJuWHW3D4dFBjoYv7rVcNkPzkWGoeDPk5ZYyeM7IhN2PRLjWiY7bJhvo/lwjLZ2ZDK/7uPYXUDjuC/ldYShJSQNhPG9WWbsMeLMD5/9Pcg/UX4sFCSEyI16PdhWjrUcTJkEjLBCSpKivBDcBM0/fdV+t/+Wpc2dXLD56GnmTabpTOpmXZhmW2XsRVfkpdB4/vr8SQPEWzZSVK5dMkzCvJIAWCMlU76WTKK8sbSdBhgMiwGRZ7EeSZ/QAn4upPAOUuRO4vtTcgzlCZtU+qQnKFPzOQwjxDpUvO34=
jobs:
  include:
  - stage: runTests
    language: java
  - stage: dockerBuild
    services:
    - docker
    before_install:
    - openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv
      -in google-key.json.enc -out google-key.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null
    - source "$HOME/google-cloud-sdk/path.bash.inc"
    - gcloud auth activate-service-account --key-file=google-key.json
    - gcloud auth configure-docker
    - gcloud config set project "${GCP_PROJECT_ID}"
    install: true
    script:
    - |-
      set -ex;
      docker login -u $DOCKER_USERNAME -p $DOCKER_KEY
      docker build -t card:${TRAVIS_COMMIT} .
      docker push $DOCKER_USERNAME/"card:${TRAVIS_COMMIT}"
      docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
      docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
      set +x
